//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuv.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prevodsr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prevodsr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tuv.Resources.Prevodsr", typeof(Prevodsr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom reseta lozinke!.
        /// </summary>
        public static string Greška_prilikom_reseta_lozinke_ {
            get {
                return ResourceManager.GetString("Greška prilikom reseta lozinke!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiran radni nalog.
        /// </summary>
        public static string Kreiran_radni_nalog {
            get {
                return ResourceManager.GetString("Kreiran radni nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiran radni nalog - izvršitelj.
        /// </summary>
        public static string Kreiran_radni_nalog___izvršitelj {
            get {
                return ResourceManager.GetString("Kreiran radni nalog - izvršitelj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreirana ponuda.
        /// </summary>
        public static string Kreirana_ponuda {
            get {
                return ResourceManager.GetString("Kreirana ponuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije definisana kursna lista za nedelju.
        /// </summary>
        public static string Nije_definisana_kursna_lista_za_nedelju {
            get {
                return ResourceManager.GetString("Nije definisana kursna lista za nedelju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvoren radni nalog.
        /// </summary>
        public static string Otvoren_radni_nalog {
            get {
                return ResourceManager.GetString("Otvoren radni nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponuda je odobrena.
        /// </summary>
        public static string Ponuda_je_odobrena {
            get {
                return ResourceManager.GetString("Ponuda je odobrena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponuda je prihvaćena.
        /// </summary>
        public static string Ponuda_je_prihvaćena {
            get {
                return ResourceManager.GetString("Ponuda je prihvaćena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponuda nije prihvaćena.
        /// </summary>
        public static string Ponuda_nije_prihvaćena {
            get {
                return ResourceManager.GetString("Ponuda nije prihvaćena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebna je revizija ponude.
        /// </summary>
        public static string Potrebna_je_revizija_ponude {
            get {
                return ResourceManager.GetString("Potrebna je revizija ponude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplata je veća od fakture.
        /// </summary>
        public static string Uplata_je_veća_od_fakture {
            get {
                return ResourceManager.GetString("Uplata je veća od fakture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno promenjena lozinka.
        /// </summary>
        public static string Uspešno_promenjena_lozinka {
            get {
                return ResourceManager.GetString("Uspešno promenjena lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvoren radni nalog.
        /// </summary>
        public static string Zatvoren_radni_nalog {
            get {
                return ResourceManager.GetString("Zatvoren radni nalog", resourceCulture);
            }
        }
    }
}
